//Project Euler Problem 02
//By: Brandon Shearrer
//CS 2 Spring 2018

/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

/**
*@author 		Brandon Shearrer
*@version		1.0
*@date			2/25/2018
*/

public class P2
{

	public static int sum = 0;
	public static int firstnum = 1;
	public static int secondnum = 2;

	public static void main(String[] args) 
	{
		System.out.println(Fibonacci());
	}

	public static int Fibonacci() 
	{	

		while (firstnum <= 4000000) 
		{
			if (firstnum % 2 == 0)
			{
				sum += firstnum;
			}
			int z = firstnum + secondnum;
			firstnum = secondnum;
			secondnum = z;
		}
		return sum;
	}
}